### ISSUE TITLE
New node cannot join after the first node stopped

### ISSUE THREAD

**Issue by ZihanTang** [nknorg/nkn#160]
I started 8 nodes following the instruction and stop the very first one which created the network. New node failed to join with following logs.
```
xhdeMacBook-Air-5:node9 xh$ ./nknd -test join
2018/06/13 15:45:18.465413 [TRACE] GID 1, nknMain() nknd.go:80 Node version:  v0.1-alpha-2-g68d1
2018/06/13 15:45:18.465492 [TRACE] GID 1, JoinNet() chord.go:295
panic: runtime error: index out of range

goroutine 18 [running]:
github.com/nknorg/nkn/net/chord.trimSlice(0x184d258, 0x0, 0x0, 0x184d258, 0x0, 0x0)
	/Users/xh/go/src/github.com/nknorg/nkn/net/chord/net.go:821 +0x86
github.com/nknorg/nkn/net/chord.(*TCPTransport).handleConn(0xc42005e240, 0xc420134000)
	/Users/xh/go/src/github.com/nknorg/nkn/net/chord/net.go:699 +0x9c7
created by github.com/nknorg/nkn/net/chord.(*TCPTransport).listen
	/Users/xh/go/src/github.com/nknorg/nkn/net/chord/net.go:636 +0x14e
```
or
```
xhdeMacBook-Air-5:node9 xh$ ./nknd -test join
2018/06/13 15:45:15.441674 [TRACE] GID 1, nknMain() nknd.go:80 Node version:  v0.1-alpha-2-g68d1
2018/06/13 15:45:15.443488 [TRACE] GID 1, JoinNet() chord.go:295
2018/06/13 15:45:15.449267 [FATAL] GID 1, failed to join local node! Got %s EOF
```

**Comment by doraemon0** [comment]
Hi @ZihanTang , thanks for reporting! Let us have a look.

**Comment by yilunzhang** [comment]
It seems that the SeedList you are using is pointing towards the first node (which is already dead). SeedList must be pointing towards a live node at the point of joining.

**Comment by ZihanTang** [comment]
thanks for explaination. I’ll close this one and try again. Good luck
