### ISSUE TITLE
Chord FindSuccessors met nil Pointer panic during startup

### ISSUE THREAD

**Issue by gdmmx** [nknorg/nkn#241]
### Description of the issue
CI testing large-scale startup, from 1 create node outspread to 120 nodes suddenly,  one node met nil Pointer panic during the first time FindSuccessors.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
latest version of dev-testing branch
- [x] This issue has not been reported earlier.

### Your environment
* OS
Debian GNU/Linux 9 (stretch)
* Go version
go version go1.10.3 linux/amd64
* Release tag/commit of the code
v0.1-alpha-103-ge3abc

### Expected behaviour
What should happen?
node join NKN network successful and participate in consensus activity.

### Actual behaviour
What is actually happening?
Panic due to met nil Pointer at first time FindSuccessors().

### Steps to reproduce
1. Provide detailed steps
* Running the first node(create node)
* Booting 120 VMs to join nkn from create node at the same time

2. how to reproduce this issue
Refer to above.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
```
2018/08/27 10:33:27.207151 [INFO ] GID 1, Node version:  v0.1-alpha-103-ge3abc
2018/08/27 10:33:27 GetNodeState: {"id":0,"jsonrpc":"2.0","result":{"State":0,"SyncState":"PersistFinished","Port":0,"NodePort":30001,"ChordPort":30000,"JsonPort":30003,"WsPort":30002,"Addr":"35.197.90.102","ID":12549842751938768130,"Time":1535366007409311215,"Version":0,"Services":0,"Relay":true,"Height":0,"TxnCnt":0,"RxTxnCnt":0,"ChordID":"1628b492a9b6b0a1d2f207a8cd2d65e3e0883034005538cf9b06f70ed29f4ca6"}}
2018/08/27 10:33:27 NodeInfo: {2.0 0 {0 PersistFinished 0 30001 30000 30003 30002 35.197.90.102 12549842751938768130 1535366007409311215 0 0 true 0 0 0 1628b492a9b6b0a1d2f207a8cd2d65e3e0883034005538cf9b06f70ed29f4ca6}}
2018/08/27 10:33:27.481611 [INFO ] GID 1, Connect to Seed [35.197.90.102:30003] successful
2018/08/27 10:33:27 genId(35.234.137.35:30000@0) = 9c56c2d24cf17c5ae49e04b2a62c9c0c70409f4f19566951a25e4e26b51be1ef
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7661a6]

goroutine 26 [running]:
panic(0x904260, 0xc918f0)
	/usr/lib/go-1.10/src/runtime/panic.go:551 +0x3c1 fp=0xc420167a48 sp=0xc4201679a8 pc=0x42aed1
runtime.panicmem()
	/usr/lib/go-1.10/src/runtime/panic.go:63 +0x5e fp=0xc420167a68 sp=0xc420167a48 pc=0x429dae
runtime.sigpanic()
	/usr/lib/go-1.10/src/runtime/signal_unix.go:388 +0x17a fp=0xc420167ab8 sp=0xc420167a68 pc=0x43ffba
github.com/nknorg/nkn/net/chord.(*localVnode).FindSuccessors(0xc420370aa0, 0x1, 0xc42035ee40, 0x20, 0x20, 0x8f3b40, 0xc4203c66c8, 0xc42003e508, 0x92ba80, 0xc4202700c0)
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/vnode.go:319 +0x56 fp=0xc420167bc0 sp=0xc420167ab8 pc=0x7661a6
github.com/nknorg/nkn/net/chord.(*TCPTransport).handleConn(0xc420068e40, 0xc42000e890)
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/net.go:772 +0xf7a fp=0xc420167fd0 sp=0xc420167bc0 pc=0x76076a
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420167fd8 sp=0xc420167fd0 pc=0x457a51
created by github.com/nknorg/nkn/net/chord.(*TCPTransport).listen
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/net.go:651 +0x227
```

**Comment by gdmmx** [comment]
Fixed at commit 501a91150...
