### ISSUE TITLE
nil pointer crash when checkPredecessor in Chord stabilize

### ISSUE THREAD

**Issue by gdmmx** [nknorg/nkn#337]
### Description of the issue
**nknd crashed** 

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
Debian GNU/Linux 9 (stretch)
* Go version
go version go1.11 linux/amd64
* Release tag/commit of the code
commit 3b324d2651e7b67c

### Expected behaviour
No crash in any time.

### Actual behaviour
![image](https://user-images.githubusercontent.com/31470624/47195754-d8730200-d38f-11e8-9382-2d0a7de39678.png)

### Steps to reproduce
Unknown. Can't reproduce every time.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
```
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 217.61.112.242:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 104.199.252.161:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 3 chord nodes at 35.237.147.141:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 185.228.232.153:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 188.65.233.36:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 35.231.16.126:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 89.36.220.154:30000.
2018/10/19 02:48:38 [INFO] Disconnect with 1 chord nodes at 35.194.83.8:30000.
2018/10/19 02:48:39 [ERR] Error notifying predecessor: Predecessor is nil
2018/10/19 02:48:39.688089 [WARN ] GID 512, Failed to contact 3a4a8b137999b47f76aed2931aee6fc9888d9492696df0d6bb334c87222222ae. Got write tcp 10.168.0.9:46246->165.227.216.166:30000: write: broken pipe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x861da5]

goroutine 12394 [running]:
github.com/nknorg/nkn/net/chord.(*localVnode).checkPredecessor(0xc0003781e0, 0x0, 0x0)
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/vnode.go:368 +0x95
github.com/nknorg/nkn/net/chord.(*localVnode).stabilize(0xc0003781e0)
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/vnode.go:125 +0x1d4
github.com/nknorg/nkn/net/chord.(*localVnode).stabilize-fm()
	/home/admin/nknorg/src/github.com/nknorg/nkn/net/chord/vnode.go:79 +0x2a
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```

**Comment by yilunzhang** [comment]
Fixed in #347
