### ISSUE TITLE
Concurrent map read and write in StateDB

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#611]
```
fatal error: concurrent map writes

goroutine 106 [running]:
runtime.throw(0x189d122, 0x15)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:617 +0x72 fp=0xc00822d8e0 sp=0xc00822d8b0 pc=0x102da52
runtime.mapassign_faststr(0x17a9da0, 0xc002ab6180, 0xc00351c810, 0x2c, 0xc00351c810)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/map_faststr.go:291 +0x40f fp=0xc00822d948 sp=0xc00822d8e0 pc=0x10148bf
github.com/nknorg/nkn/chain/db.(*StateDB).getPubSub(0xc002de3180, 0xc0051fef40, 0x2c, 0x40, 0x20, 0x20, 0xc00652f840)
	/Users/skysniper/Documents/nkn/nkn/chain/db/pubsub.go:125 +0x20d fp=0xc00822da00 sp=0xc00822d948 pc=0x16aa88d
github.com/nknorg/nkn/chain/db.(*StateDB).isSubscribed(0xc002de3180, 0xc0082a8b00, 0xff, 0xe9a3294b00000000, 0xc00613fee0, 0x20, 0x20, 0xc00652f840, 0x40, 0x5d9d7bdbe9a3294b, ...)
	/Users/skysniper/Documents/nkn/nkn/chain/db/pubsub.go:211 +0xb1 fp=0xc00822da68 sp=0xc00822da00 pc=0x16ab6d1
github.com/nknorg/nkn/chain/db.(*ChainStore).IsSubscribed(0xc000154000, 0xc0082a8b00, 0xff, 0x0, 0xc00613fee0, 0x20, 0x20, 0xc00652f840, 0x40, 0x20, ...)
	/Users/skysniper/Documents/nkn/nkn/chain/db/pubsub.go:220 +0x96 fp=0xc00822dad8 sp=0xc00822da68 pc=0x16ab7f6
github.com/nknorg/nkn/chain.VerifyTransactionWithLedger(0xc005748c40, 0x0, 0x0)
	/Users/skysniper/Documents/nkn/nkn/chain/txValidator.go:340 +0xb86 fp=0xc00822ddd0 sp=0xc00822dad8 pc=0x158a8c6
github.com/nknorg/nkn/chain/pool.(*TxnPool).AppendTxnPool(0xc0000ecbb0, 0xc005748c40, 0x20, 0x20)
	/Users/skysniper/Documents/nkn/nkn/chain/pool/txpool.go:55 +0x167 fp=0xc00822de38 sp=0xc00822ddd0 pc=0x1591727
github.com/nknorg/nkn/node.(*LocalNode).handleTransactionsMessage(0xc0002dc0e0, 0xc005748be0, 0x1, 0x0, 0x0)
	/Users/skysniper/Documents/nkn/nkn/node/transaction.go:358 +0x1a7 fp=0xc00822df18 sp=0xc00822de38 pc=0x1601c47
github.com/nknorg/nkn/node.(*LocalNode).startReceivingTxnMsg.func1(0xc0002dc0e0, 0xc0000bc9c0)
	/Users/skysniper/Documents/nkn/nkn/node/transaction.go:235 +0x176 fp=0xc00822dfd0 sp=0xc00822df18 pc=0x1606436
runtime.goexit()
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00822dfd8 sp=0xc00822dfd0 pc=0x105a301
created by github.com/nknorg/nkn/node.(*LocalNode).startReceivingTxnMsg
	/Users/skysniper/Documents/nkn/nkn/node/transaction.go:227 +0x66
```

This might occur (very rare though) when verification are persist are called at the same time. We probably need to change all maps in StateDB to sync.Map.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [ ] This issue has not been reported earlier.

**Comment by yilunzhang** [comment]
Fixed in #617
